# Generated by Django 4.2.2 on 2024-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
