# Generated by Django 4.2.2 on 2024-06-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_mailing_next_send_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='clients',
            new_name='client',
        ),
    ]
