# Generated by Django 4.2.2 on 2024-07-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_rename_clients_mailing_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_change_status', 'Может менять статус')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
